
<div class="row">
     <section class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
       <header><h2 class="titulo-nav">Aventurate en Felipe Carrillo Puerto</h2></header>
       <article class="row">
       <header><h3 class="titulo-nav">Galería de Felipe Carrillo Puerto</h3></header>           
          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 galeria">
            <img src="img/ceiba.jpg" class="img-responsive" alt="">
          </div>
          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 galeria">
            <img src="img/ceiba.jpg" class="img-responsive" alt="">
          </div>
          <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 galeria">
            <img src="img/ceiba.jpg" class="img-responsive" alt="">
          </div>

       </article>
       <article class="row">
        <header><h3 class="titulo-nav">Acerca del Municipio</h3></header>
          <section class="col-md-7 video">
            <header><h3 class="sr-only">Video Acerca del Municipio</h3></header>
            <video src="videos/zapatos_nuevos.mp4" controls="controls" width="400"></video>
         
          </section>
          <aside class="col-md-5 panel panel-default">
            <header class="panel-heading"><h2>Servicios</h2></header>
            <section class="panel-body">
              <a href="" class="text-primary"><h3><span class="glyphicon glyphicon-cutlery"></span> Donde Comer</h3></a>
              <a href="" class="text-primary"><h3><span class="glyphicon glyphicon-header"></span> Donde Dormir</h3></a>
              <a href="" class="text-primary"><h3><span class="glyphicon glyphicon-glass"></span> Bares</h3></a>

            </section>
          </aside>
       </article>
       
     </section>

     <aside class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
      <header> <h2 class="sr-only">Información</h2></header>
       <article>
         <header> <h3 class="titulo-nav">Mapa <abbr title="Felipe Carrillo Puerto">FCP</abbr></h3></header>
         <img src="img/mapa.jpg" class="img-responsive" alt="Mapa de Felipe Carrillo Puerto A
        Quintana Roo"> 
       </article>
       <article class="panel panel-default">
         <header class="panel-heading"><h2>Otros Servicios</h2></header>
            <section class="panel-body">
              <a href="" class="text-primary"><h3><span class="glyphicon glyphicon-road"></span> Transporte</h3></a>
              <a href="" class="text-primary"><h3><span class="glyphicon glyphicon-info-sign"></span> Más Información</h3></a>
              

            </section>
       </article>
     </aside>
    </div>
  