<!doctype html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<link rel="shortcut icon" type="image/png" href="img/iglesia.png">
	<title>Filipe Carrillo Puerto</title>
	<link rel="stylesheet" href="css/bootstrap.min.css">
	<link rel="stylesheet" href="css/miestilo.css">
	
	

</head>
<body>
	<div class="container">
	
		<header class="row justificado">
			<div class="col-lg-1 col-md-1 col-sm-2 col-xs-2"> <img class="img-responsive" src="img/logo_fcp.png" alt=""> </div>
			<div class="col-lg-6 col-md-6 col-sm-3 hidden-xs"><h1>Felipe Carrillo Puerto</h1>
			</div>
			<div class="col-lg-2 col-md-2 col-sm-3 col-xs-5 ">Botones de twwiter y facxebook</div>
			<div class="col-lg-2 col-md-2 col-sm-2 col-xs-3"><img src="img/logo mexico.jpg" alt="" class="img-responsive"></div>
			<div class="col-lg-1 col-md-1 col-sm-2 col-xs-2"><img src="img/EscudoQRoo.jpg"  alt="" class="img-responsive"></div>
		</header>
		
	
