<nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand hidden-md hidden-lg hidden-sm" href="#"><h3 class="titulo-nav"> Zona Maya</h3></a>
        </div>
      
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav">
            <li class="dropdown navegacion active"><a href="?pag=inicio.inc" class="btn btn-lg" ><span class="glyphicon glyphicon-home"></span> Inicio</a></li>
            <li class="dropdown navegacion">
              <a href="?pag=aventura.inc" class="dropdown-toggle btn btn-lg js-activated" data-toggle="dropdown"  data-target="?pag=aventura.inc"> <span class="glyphicon glyphicon-globe"></span> Aventurate <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a class="btn btn-md" href="?pag=aventura.inc">Arqueología</a></li>
                <li><a class="btn btn-md" href="?pag=aventura.inc">Bellezas Naturales</a></li>
                <li><a class="btn btn-md" href="?pag=aventura.inc">Ecoturismo</a></li>
                <li><a class="btn btn-md" href="?pag=aventura.inc">Pueblos Emblematicos</a></li>
              </ul>
            </li>
             <li class="dropdown navegacion">
              <a href="#" class="dropdown-toggle btn btn-lg js-activated" data-toggle="dropdown"><span class="glyphicon glyphicon-glass"></span> Vive <abbr title="Felipe Carrillo Puerto">FCP</abbr> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a class="btn btn-md" href="#">Comiendo</a></li>
                <li><a class="btn btn-md" href="#">Conociendo</a></li>
                <li><a class="btn btn-md" href="#">Bailando</a></li>
                <li><a class="btn btn-md" href="#">Divertiendo</a></li>
              </ul>
            </li>
            <li class="dropdown navegacion">
              <a href="#" class="dropdown-toggle btn btn-lg js-activated" data-toggle="dropdown" > <span class="glyphicon glyphicon-picture"></span> Conoce<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a class="btn btn-md" href="#">Ruta 1</a></li>
                <li><a class="btn btn-md" href="#">Ruta 2</a></li>
                <li><a class="btn btn-md" href="#">Ruta 3</a></li>
                <li><a class="btn btn-md" href="#">Ruta 5</a></li>
              </ul>
            </li>
            <li class="dropdown navegacion">
              <a href="#" class="dropdown-toggle btn btn-lg js-activated" data-toggle="dropdown" ><span class="glyphicon glyphicon-star"></span> Diviertete<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a class="btn btn-md" href="#">Fiestas Tradicionales</a></li>
                <li><a class="btn btn-md" href="#">Centros Nocturnos</a></li>
                <li><a class="btn btn-md" href="#">Balnearios</a></li>
                <li><a class="btn btn-md" href="#">Fiestas Culturales</a></li>
              </ul>
            </li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </nav>